Controllers/AdminController.cs
using HienTangToc.Services;
using Microsoft.AspNetCore.Mvc;

namespace HienTangToc.Controllers
{
    public class AdminController : Controller
    {
        private readonly StatisticsService _statisticsService;

        public AdminController(StatisticsService statisticsService)
        {
            _statisticsService = statisticsService;
        }

        public IActionResult Admin()
        {
            var userRole = HttpContext.Session.GetString("UserRole");

            int soNguoiHien = _statisticsService.CountNguoiHien();
            int soNguoiMuon = _statisticsService.CountNguoiMuon();
            int soSalon = _statisticsService.CountSalon();
            int soToc = _statisticsService.CountToc();
            Console.WriteLine($"Số người hiến tóc: {soNguoiHien}");
            Console.WriteLine($"Số người mượn tóc: {soNguoiMuon}");
            Console.WriteLine($"Số người salon tóc: {soSalon}");
            Console.WriteLine($"Số người salon tóc: {soToc}");

            ViewData["SoNguoiHien"] = soNguoiHien;
            ViewData["SoNguoiMuon"] = soNguoiMuon;
            ViewData["SoSalon"] = soSalon;
            ViewData["SoToc"] = soToc;

            if (userRole != "admin")
            {
                return RedirectToAction("Index", "Home");
            }
            var userName = HttpContext.Session.GetString("UserName");

            // Truyền tên người dùng vào ViewData
            ViewData["UserName"] = userName;

            return View();
        }
    }
}

Controllers/FromController.cs
using HienTangToc.Models;
using HienTangToc.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;

namespace HienTangToc.Controllers
{
    public class FromController : Controller
    {
        private readonly NguoihienService _nguoiHienService;
        private readonly NguoimuonService _nguoiMuonService;
        private readonly SalonService _salonService;

        public FromController(NguoihienService nguoiHienService, NguoimuonService nguoiMuonService, SalonService salonService)
        {
            _nguoiHienService = nguoiHienService;
            _nguoiMuonService = nguoiMuonService;
            _salonService = salonService;
        }

        // GET: /From/Hientoc
        [HttpGet]
        public IActionResult Hientoc()
        {
            return View();
        }

        // POST: /From/Hientoc
        [HttpPost]
        public async Task<IActionResult> CreateHientoc(NguoihienModel model)
        {
            if (ModelState.IsValid)
            {
                var (nguoiHien, message) = await _nguoiHienService.CreateNguoihienAsync(model);

                if (nguoiHien != null)
                {
                    TempData["SuccessMessage"] = message; // Thông báo thành công
                    return RedirectToAction("Hientoc");
                }
                else
                {
                    TempData["ErrorMessage"] = message; // Thông báo lỗi
                }
            }
            return View("Hientoc", model);
        }

        [HttpGet]
        public IActionResult Muontoc()
        {
            return View();
        }

        // POST: /From/Muontoc
        [HttpPost]
        public async Task<IActionResult> CreateMuontoc([FromForm] NguoimuonModel model)
        {
            if (ModelState.IsValid)
            {
                var (nguoiMuon, message) = await _nguoiMuonService.CreateNguoimuonAsync(model);

                if (nguoiMuon != null)
                {
                    TempData["SuccessMessage"] = message; // Thông báo thành công
                    return RedirectToAction("Muontoc");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, message); // Thông báo lỗi
                }
            }
            return View("Muontoc", model);
        }

        [HttpGet]
        public IActionResult Salontoc()
        {
            return View();
        }

        // POST: /From/Salontoc
        [HttpPost]
        public async Task<IActionResult> CreateSalontoc([FromForm] SalonModel salon, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                var (resultSalon, message) = await _salonService.CreateSalonAsync(salon, imageFile);

                if (resultSalon != null)
                {
                    TempData["SuccessMessage"] = message; // Thông báo thành công
                    return RedirectToAction("Salontoc");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, message); // Thông báo lỗi
                }
            }
            return View("Salontoc", salon);
        }

        // GET: /From/Success
        [HttpGet]
        public IActionResult Success()
        {
            return View();
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using HienTangToc.Interface;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

public class LoginController : Controller
{
    private readonly UserInterface _userService;

    public LoginController(UserInterface userService)
    {
        _userService = userService;
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(string emailOrPhone, string password)
    {
        if (string.IsNullOrEmpty(emailOrPhone) || string.IsNullOrEmpty(password))
        {
            ModelState.AddModelError("", "Email/Số điện thoại và mật khẩu không được để trống.");
            return View();
        }

        var user = await _userService.AuthenticateUser(emailOrPhone, password);

        if (user == null)
        {
            ModelState.AddModelError("", "Email/Số điện thoại hoặc mật khẩu không đúng.");
            return View();
        }

        HttpContext.Session.SetString("UserName", user.Name);
        HttpContext.Session.SetString("UserRole", user.Role);

        if (user.Role == "admin")
        {
            return RedirectToAction("Admin", "Admin");
        }
        else
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/UserController.cs
using HienTangToc.Interface;
using HienTangToc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace HienTangToc.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class UserController : ControllerBase
    {
        private readonly UserInterface _userService;

        public UserController(UserInterface userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public async Task<ActionResult<List<UserModel>>> GetAllUsers(int pageNumber = 1, int pageSize = 10)
        {
            var users = await _userService.GetAllUsersAsync(pageNumber, pageSize);
            return Ok(users);
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<UserModel>> GetUserById(int id)
        {
            var user = await _userService.GetUserByIdAsync(id);
            if (user == null)
            {
                return NotFound("User not found.");
            }
            return Ok(user);
        }
        

        [HttpPost("register")]
        public async Task<ActionResult> Register([FromBody] UserModel userModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var (createdUser, message) = await _userService.CreateUserAsync(userModel);
            if (createdUser == null)
            {
                return BadRequest(new { Message = message });
            }
            return CreatedAtAction(nameof(GetUserById), new { id = createdUser.Id }, createdUser);
        }



        [HttpPost]
        public async Task<ActionResult> CreateUser(UserModel user)
        {
            var (createdUser, message) = await _userService.CreateUserAsync(user);
            if (createdUser == null)
            {
                return BadRequest(message);
            }
            return CreatedAtAction(nameof(GetUserById), new { id = createdUser.Id }, createdUser);
        }


        [HttpPut("{id}")]
        public async Task<ActionResult> UpdateUser(int id, UserModel userUpdate)
        {
            var (originalUser, updatedUser, message) = await _userService.UpdateUserAsync(id, userUpdate);
            if (updatedUser == null)
            {
                return BadRequest(message);
            }
            return Ok(updatedUser);
        }

        [HttpDelete("{id}")]
        public async Task<ActionResult> DeleteUser(int id)
        {
            var (success, message) = await _userService.DeleteUserAsync(id);
            if (!success)
            {
                return NotFound(message);
            }
            return NoContent();
        }


        
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin Dashboard</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/site.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        .sidebar {
            height: 100vh;
            width: 250px;
            background-color: deeppink;
            position: fixed;
            top: 0;
            left: 0;
            transition: transform 0.3s ease;
            transform: translateX(-100%);
        }

            .sidebar.open {
                transform: translateX(0);
            }

            .sidebar a {
                color: white;
                padding: 15px;
                text-decoration: none;
                display: block;
            }

                .sidebar a:hover {
                    background-color: darkviolet;
                }

        .main-content {
            margin-left: 260px; /* Adjust based on sidebar width */
            padding: 20px;
        }

        .toggle-btn {
            position: fixed;
            top: 20px;
            left: 20px;
            background-color: deeppink;
            color: white;
            border: none;
            padding: 10px;
            cursor: pointer;
        }

        .navbar {
            padding: 0 15px;
            background-color: #f8f9fa;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="toggle-btn" onclick="toggleSidebar()">☰</button>
            <div class="nav-right">
                <ul class="nav-links">
                    <li><a asp-controller="Admin" asp-action="Admin">Home</a></li>
                    @if (ViewData["UserName"] != null)
                    {
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Hello, @ViewData["UserName"]!
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="User" asp-action="Profile">Profile</a>
                                <a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Đăng xuất</a>
                                <form id="logout-form" asp-controller="Logout" asp-action="Logout" method="post" style="display: none;">
                                </form>
                            </div>
                        </div>
                    }
                    else
                    {
                        <a asp-controller="Login" asp-action="Login">Đăng nhập</a>
                    }
                </ul>
            </div>
        </nav>

        <div class="sidebar" id="sidebar">
            <button class="toggle-btn" onclick="toggleSidebar()">&larr;</button>
            <br><br><br>
            <a href="ttuser">Thông tin tài khoản</a>
            <a href="nguoimuon">Thông tin người mượn</a>
            <a href="nguoihien">Thông tin người hiến</a>
            <a href="salon">Thông tin salon</a>
        </div>
    </header>
    <div class="main-content">
        @RenderBody()
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        function toggleSidebar() {
            var sidebar = document.getElementById('sidebar');
            sidebar.classList.toggle('open');
        }
    </script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Trang Chủ</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav>
            <div class="nav-left">
                <div class="logo">
                    <img src="~/image/logo.png" alt="Logo" />
                </div>
                <ul class="nav-links">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="dropdown">
                        <a>Thư viện tóc</a>
                        <ul class="dropdown-menu">
                            @if (ViewData["UserName"] != null)
                            {
                                <li><a asp-controller="From" asp-action="Hientoc">Đăng ký hiến tóc</a></li>
                                <li><a asp-controller="From" asp-action="Muontoc">Đăng ký mượn tóc</a></li>
                                <li><a asp-controller="From" asp-action="Salontoc">Đăng ký salon tóc</a></li>
                            }
                            else
                            {
                                <li><a asp-controller="Login" asp-action="Login">Đăng ký hiến tóc</a></li>
                                <li><a asp-controller="Login" asp-action="Login">Đăng ký mượn tóc</a></li>
                                <li><a asp-controller="Login" asp-action="Login">Đăng ký salon tóc</a></li>
                            }
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a>Salon</a>
                        <ul class="dropdown-menu">
                            @if (ViewBag.Salons != null)
                            {
                                foreach (var salon in (List<HienTangToc.Models.SalonModel>)ViewBag.Salons)
                                {
                                    <li><a asp-controller="Home" asp-action="Salon" asp-route-id="@salon.Idsl">@salon.Ten</a></li>
                                }
                            }
                            else
                            {
                                <li><a href="#">Không có salon</a></li>
                            }
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="nav-right">
                @if (ViewData["UserName"] != null)
                {
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Hello, @ViewData["UserName"]!
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-controller="User" asp-action="Profile">Profile</a>
                            <a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Đăng xuất</a>
                            <form id="logout-form" asp-controller="Logout" asp-action="Logout" method="post" style="display: none;">
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <a asp-controller="Login" asp-action="Login">Đăng nhập</a>
                }
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        @RenderBody()
    </main>
    <footer class="text-center text-lg-start text-muted mt-3" style="background-color: #f5f5f5;">
        <section class="">
            <div class="container text-center text-md-start pt-4 pb-4">
                <div class="row mt-3">
                    <div class="col-12 col-lg-3 col-sm-12 mb-2">
                        <a href="https://mdbootstrap.com/" target="_blank" class="">
                            <img src="~/image/logo.png" width="70" height="70" />
                        </a>
                        <p class="mt-2 text-dark">
                            Mạng lưới Ung thư vú Việt Nam là một thành viên của Hiệp hội Phòng chống Ung thư Quốc tế, hoạt động với mục đích tăng cường phát hiện sớm ung thư vú và nâng cao chất lượng sống cho phụ nữ trong cộng đồng.
                        </p>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-2">
                        <h6 class="text-uppercase text-dark fw-bold mb-2">
                            Liên hệ
                        </h6>
                        <ul class="list-unstyled mb-4">
                            <li><a class="text-muted" href="#">Lầu 1, Số 122/11 Phổ Quang, P.9, Q. Phú Nhuận, TP. Hồ Chí Minh</a></li>
                            <li><a class="text-muted" href="#">(+84) 961 924 300</a></li>
                            <li><a class="text-muted" href="#">pinkteam@bcnv.org.vn</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-2">
                        <h6 class="text-uppercase text-dark fw-bold mb-2">
                            Ủng hộ BCNV
                        </h6>
                        <ul class="list-unstyled mb-4">
                            <li><a class="text-muted" href="#">Gây quỹ cộng đồng</a></li>
                            <li><a class="text-muted" href="#">BCNV Store</a></li>
                            <li><a class="text-muted" href="#">Các địa điểm bán hàng gây quỹ</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-2">
                        <h6 class="text-uppercase text-dark fw-bold mb-2">
                            Thông tin
                        </h6>
                        <ul class="list-unstyled mb-4">
                            <li><a class="text-muted" href="#">Tìm hiểu về ung thư vú</a></li>
                            <li><a class="text-muted" href="#">Điều trị ung thu vú</a></li>
                            <li><a class="text-muted" href="#">Hỏi đáp về ung thư vú</a></li>
                            <li><a class="text-muted" href="#">Câu truyện truyền cảm hứng</a></li>
                        </ul>
                    </div>
                    <div class="col-12 col-sm-12 col-lg-3">
                        <h6 class="text-uppercase text-dark fw-bold mb-2">Gia Nhập </h6>
                        <p class="text-muted">Hãy nhập email của bạn vào đây</p>
                        <div class="input-group mb-3">
                            <input type="email" class="form-control border" placeholder="Email" aria-label="Email" aria-describedby="button-addon2" />
                            <button class="btn btn-light border shadow-0" type="button" id="button-addon2" data-mdb-ripple-color="dark">
                                Join
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <div class="">
            <div class="container">
                <div class="d-flex justify-content-between py-4 border-top">
                    <div>
                        <i class="fab fa-lg fa-cc-visa text-dark"></i>
                        <i class="fab fa-lg fa-cc-amex text-dark"></i>
                        <i class="fab fa-lg fa-cc-mastercard text-dark"></i>
                        <i class="fab fa-lg fa-cc-paypal text-dark"></i>
                    </div>
                   
                    <div class="back-to-top">
                        <a href="#" id="Top" class="scroll-link">Back to Top ^</a>
                    </div>

                    <style>
                        .back-to-top {
                            position: fixed;
                            bottom: 20px;
                            right: 20px;
                        }

                        .scroll-link {
                            display: none; 
                            font-size: 16px;
                            text-decoration: underline;
                            color: #007bff;
                            cursor: pointer;
                        }

                            .scroll-link:hover {
                                color: #0056b3;
                            }
                    </style>
                    <script>
                        const Top = document.getElementById("Top");

                        window.onscroll = function () {
                            if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
                                Top.style.display = "block";
                            } else {
                                Top.style.display = "none";
                            }
                        };

                        Top.addEventListener("click", function (e) {
                            e.preventDefault();
                            window.scrollTo({
                                top: 0,
                                behavior: "smooth"
                            });
                        });
                    </script>
</body>
</html>

Views/Shared/_SalonMenu.cshtml
@model IEnumerable<HienTangToc.Models.SalonModel>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Salon <span class="caret"></span></a>
    <ul class="dropdown-menu">
        @foreach (var salon in Model)
        {
            <li><a asp-controller="Home" asp-action="Salon" asp-route-id="@salon.Idsl">@salon.Ten</a></li>
        }
    </ul>
</li>